//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloCoreAdminMvc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdministratorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdministratorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelloCoreAdminMvc.Resources.AdministratorResources", typeof(AdministratorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Administratoren sind registriert..
        /// </summary>
        public static string AdministratorCount_Many {
            get {
                return ResourceManager.GetString("AdministratorCount_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist kein Administrator registriert..
        /// </summary>
        public static string AdministratorCount_None {
            get {
                return ResourceManager.GetString("AdministratorCount_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Administrator ist registriert..
        /// </summary>
        public static string AdministratorCount_One {
            get {
                return ResourceManager.GetString("AdministratorCount_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administratoren.
        /// </summary>
        public static string Administrators {
            get {
                return ResourceManager.GetString("Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Masteradministratoren sind registriert..
        /// </summary>
        public static string MasterAdministratorCount_Many {
            get {
                return ResourceManager.GetString("MasterAdministratorCount_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist kein Masteradministrator registriert..
        /// </summary>
        public static string MasterAdministratorCount_None {
            get {
                return ResourceManager.GetString("MasterAdministratorCount_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Masteradministrator ist registriert..
        /// </summary>
        public static string MasterAdministratorCount_One {
            get {
                return ResourceManager.GetString("MasterAdministratorCount_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administratoren.
        /// </summary>
        public static string Menu_Administrators {
            get {
                return ResourceManager.GetString("Menu_Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Projektadministratoren sind registriert..
        /// </summary>
        public static string ProjectAdministratorCount_Many {
            get {
                return ResourceManager.GetString("ProjectAdministratorCount_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist kein Projektadministrator registriert..
        /// </summary>
        public static string ProjectAdministratorCount_None {
            get {
                return ResourceManager.GetString("ProjectAdministratorCount_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Projektadministrator ist registriert..
        /// </summary>
        public static string ProjectAdministratorCount_One {
            get {
                return ResourceManager.GetString("ProjectAdministratorCount_One", resourceCulture);
            }
        }
    }
}
